CREATE OR REPLACE PROCEDURE ADD_TRADE
( P_TRADE_ID NUMBER,
P_CUSTOMER_ID NUMBER,
P_INSTRUMENT_ID NUMBER,
P_AMOUNT NUMBER)
AS
BEGIN
INSERT INTO TRADES (TRADE_ID,
        CUSTOMER_ID,
        INSTRUMENT_ID,
        TRADE_AMOUNT,
        TRADE_DATE,
        STATUS) VALUES(P_TRADE_ID,P_CUSTOMER_ID,P_INSTRUMENT_ID,P_AMOUNT,SYSDATE,'PENDING');

INSERT INTO trade_audit( AUDIT_ID, TRADE_ID, ACTION_TYPE,ACTION_DATE) 
VALUES(AUDIT_SEQ.NEXTVAL,P_TRADE_ID,'TRADE_CREATED',SYSDATE);
        
COMMIT;
END;
/


