CREATE OR REPLACE PROCEDURE APPROVE_TRADE(P_TRADE_ID NUMBER)
AS
 V_COUNT NUMBER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM TRADES WHERE TRADE_ID=P_TRADE_ID;
IF V_COUNT=0 THEN
RAISE_APPLICATION_ERROR (-20001,'TRADE DOES NOT EXIST');
END IF;

UPDATE TRADES SET STATUS='APPROVED' WHERE TRADE_ID = P_TRADE_ID;

INSERT INTO TRADE_AUDIT (AUDIT_ID,TRADE_ID,ACTION_TYPE,ACTION_DATE) 
VALUES(AUDIT_SEQ.NEXTVAL,P_TRADE_ID,'APPROVED',SYSDATE);
COMMIT;

END;
/