CREATE OR REPLACE TRIGGER TRG_TRIGGER_AUDIT
AFTER INSERT ON TRADES
FOR EACH ROW
BEGIN
INSERT INTO TRADE_AUDIT (AUDIT_ID,TRADE_ID,action_type,ACTION_DATE) 
VALUES(AUDIT_SEQ.NEXTVAL,:NEW.TRADE_ID,'TRADE CREATED',SYSDATE);
END;
/
