CREATE TABLE TRADES
(
    TRADE_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    INSTRUMENT_ID NUMBER,
    TRADE_AMOUNT NUMBER(15,2),
    TRADE_DATE DATE,
    STATUS VARCHAR2(20),

    CONSTRAINT FK_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),

    CONSTRAINT FK_INSTRUMENT
        FOREIGN KEY (INSTRUMENT_ID)
        REFERENCES INSTRUMENTS(INSTRUMENT_ID)
);