CREATE OR REPLACE TRIGGER TRG_TRADE_APPROVAL_AUDIT
AFTER UPDATE OF STATUS ON TRADES
FOR EACH ROW
BEGIN
INSERT INTO TRADE_AUDIT (AUDIT_ID,TRADE_ID,ACTION_TYPE,ACTION_DATE)
VALUES (AUDIT_SEQ.NEXTVAL,:NEW.TRADE_ID, 'TRADE_APPROVED',SYSDATE);
END;
/