CREATE OR REPLACE VIEW VW_TRADE_DETAILS AS
SELECT 
T.TRADE_ID,
C.CUSTOMER_NAME,
I.INSTRUMENT_NAME,
T.TRADE_AMOUNT,
T.STATUS,
T.TRADE_DATE FROM TRADES T JOIN CUSTOMERS C ON T.CUSTOMER_ID = C.CUSTOMER_ID
JOIN INSTRUMENTS I ON T.INSTRUMENT_ID= I.INSTRUMENT_ID;

